#!/bin/bash

adresFrom=$1
adresTo=$3
ras=$2
md5From=0
md5To=1
i=0
cd || exit

if 

# HELP
if [[ $1 = --help ]]
then
echo "Use ./OS [adres from] [type] [adres to]"
echo
echo "Не паникуй, ща всё будет"
echo "Смотри, вбиваешь полный адрес места, откуда хочешь копировать,"
echo "потом буквы расширения и после этого полный адрес места,"
echo "куда хочешь капировать. Не забудь после адреса поставить /"
echo "Пример: ./OS Desktop/OSi/in/ docx Desktop/"
else

while [[ "$md5From" != "$md5To" ]]
do
# create copy in zip and replace it in directory
cd "$adresFrom" || exit
zip -9q temporary.zip $(find . -name "*""$ras")
cd || exit
cp "$adresFrom""temporary.zip" "$adresTo""Backup of [""$ras""].zip"
rm "$adresFrom""temporary.zip"

# create and chek md5sum
md5From=($(md5sum "$adresFrom"*".""$ras"|sort))
mkdir /home/kali/temporary
unzip -q "$adresTo""/Backup of [""$ras""].zip" -d /home/kali/temporary
md5To=($(md5sum "/home/kali/temporary/"*|sort))
rm -Rf /home/kali/temporary
((i++)) || true
echo "Попытка номер: ""$i"
# echo $md5From
# echo $md5To

if [[ $i -gt 10 ]]
then
break
else
continue
fi
done

if [[ $i -le 10 ]]
then
echo "Всё хорошо, мы успешно сделали сохранение в файл /""$adresTo""Backup of [""$ras""].zip"
else
echo "У меня не получилось сделать сохранение"
fi
fi